
import { createClient } from '@supabase/supabase-js';
import { Customer, Admin } from '../types';

/**
 * --- BULLETPROOF SQL SETUP ---
 * Copy and run this in your Supabase SQL Editor:
 * 
 * CREATE TABLE IF NOT EXISTS customers (
 *   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 *   created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
 *   name TEXT NOT NULL,
 *   mobile TEXT NOT NULL,
 *   customer_id TEXT UNIQUE NOT NULL,
 *   stamps INTEGER DEFAULT 0,
 *   redeems INTEGER DEFAULT 0,
 *   lifetime_stamps INTEGER DEFAULT 0,
 *   tier_1_claimed BOOLEAN DEFAULT FALSE,
 *   is_deleted BOOLEAN DEFAULT FALSE
 * );
 * 
 * CREATE TABLE IF NOT EXISTS admins (
 *   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 *   username TEXT UNIQUE NOT NULL,
 *   password TEXT NOT NULL,
 *   email TEXT UNIQUE NOT NULL,
 *   security_question TEXT NOT NULL,
 *   security_answer TEXT NOT NULL
 * );
 * 
 * -- Repair script for existing tables
 * DO $$ BEGIN 
 *   IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='admins' AND column_name='email') THEN
 *     ALTER TABLE admins ADD COLUMN email TEXT;
 *     ALTER TABLE admins ADD CONSTRAINT admins_email_key UNIQUE (email);
 *   END IF;
 * END $$;
 */

const SUPABASE_URL = 'https://teyzbkdywrwukpbrwfti.supabase.co'; 
const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRleXpia2R5d3J3dWtwYnJ3ZnRpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjYyMzc1OTcsImV4cCI6MjA4MTgxMzU5N30.ok3r9DstEcMuoxbgfjEHlP3O6EA-UIgHXR4Wbkn6l4A';

export const supabase = createClient(SUPABASE_URL, SUPABASE_ANON_KEY);

export const storageService = {
  // --- Customer Methods ---
  fetchCustomers: async (): Promise<Customer[]> => {
    try {
      const { data, error } = await supabase
        .from('customers')
        .select('*')
        .eq('is_deleted', false)
        .order('created_at', { ascending: false });

      if (error) throw error;
      return data as Customer[];
    } catch (err) {
      console.error('Fetch Customers Error:', err);
      return [];
    }
  },

  addCustomer: async (name: string, mobile: string): Promise<Customer> => {
    // Generate MSC ID based on count
    const { count } = await supabase.from('customers').select('*', { count: 'exact', head: true });
    const nextCount = (count || 0) + 1;
    const customerId = `MSC${nextCount.toString().padStart(4, '0')}`;

    const { data, error } = await supabase
      .from('customers')
      .insert([{
          name: name.trim(),
          mobile: mobile.trim(),
          customer_id: customerId,
          stamps: 0,
          redeems: 0,
          lifetime_stamps: 0,
          tier_1_claimed: false,
          is_deleted: false,
      }])
      .select().single();

    if (error) throw new Error(error.message);
    return data as Customer;
  },

  updateCustomer: async (id: number, updates: Partial<Customer>) => {
    const { error } = await supabase.from('customers').update(updates).eq('id', id);
    if (error) throw new Error(error.message);
  },

  deleteCustomerSoft: async (id: number) => {
    await storageService.updateCustomer(id, { is_deleted: true });
  },

  findCustomer: async (query: string): Promise<Customer | undefined> => {
    const cleanQuery = query.trim();
    if (!cleanQuery) return undefined;

    const { data, error } = await supabase
      .from('customers')
      .select('*')
      .or(`customer_id.ilike.%${cleanQuery}%,mobile.eq.${cleanQuery}`)
      .eq('is_deleted', false)
      .maybeSingle();

    if (error) {
      console.error('Find Customer Error:', error);
      return undefined;
    }
    return data as Customer;
  },

  // --- Admin Methods ---
  addAdmin: async (admin: Admin): Promise<{ success: boolean; message: string }> => {
    const cleanUsername = admin.username.toLowerCase().trim();
    const cleanEmail = admin.email.toLowerCase().trim();
    const cleanAnswer = admin.securityAnswer.toLowerCase().trim();

    const { error } = await supabase
      .from('admins')
      .insert([{
          username: cleanUsername,
          password: admin.password,
          email: cleanEmail,
          security_question: admin.securityQuestion,
          security_answer: cleanAnswer,
      }]);
    
    if (error) {
      if (error.code === '23505') {
        return { success: false, message: "Staff ID or Email already exists." };
      }
      if (error.message.includes('column "email" of relation "admins" does not exist')) {
        return { success: false, message: "CRITICAL: Table update required. Please run the REPAIR SQL in Supabase Editor." };
      }
      if (error.code === '42P01') {
        return { success: false, message: "CRITICAL: The 'admins' table is missing entirely. Run the SETUP SQL in Supabase Editor." };
      }
      return { success: false, message: "Vault Error: " + error.message };
    }
    return { success: true, message: "Staff member successfully enrolled!" };
  },

  findAdmin: async (username: string): Promise<Admin | undefined> => {
    const cleanUsername = username.toLowerCase().trim();
    try {
        const { data, error } = await supabase
          .from('admins')
          .select('*')
          .eq('username', cleanUsername)
          .maybeSingle();

        if (error) {
            console.error("Admin DB Error:", error);
            return undefined;
        }
        if (!data) return undefined;

        return {
          username: data.username,
          password: data.password,
          email: data.email,
          securityQuestion: data.security_question,
          securityAnswer: data.security_answer
        } as Admin;
    } catch (e) {
        return undefined;
    }
  },

  findAdminByEmail: async (email: string): Promise<Admin | undefined> => {
    const cleanEmail = email.toLowerCase().trim();
    const { data, error } = await supabase
      .from('admins')
      .select('*')
      .eq('email', cleanEmail)
      .maybeSingle();

    if (error || !data) return undefined;
    return {
      username: data.username,
      password: data.password,
      email: data.email,
      securityQuestion: data.security_question,
      securityAnswer: data.security_answer
    } as Admin;
  },

  updateAdminPassword: async (email: string, newPassword: string) => {
    const cleanEmail = email.toLowerCase().trim();
    const { error } = await supabase
      .from('admins')
      .update({ password: newPassword })
      .eq('email', cleanEmail);

    if (error) throw new Error(error.message);
  }
};
