name: Keep Supabase Alive

on:
  schedule:
    # Runs at 00:00 UTC every day (Once every 24 hours)
    - cron: '0 0 * * *'
  workflow_dispatch: # Allows you to run it manually button click

jobs:
  ping_db:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Ping Database
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: node scripts/ping.js
